name: OnlineJudge - admin
on:
  push:
    branches:
      - main
  pull_request:
    branches: 'main'

jobs:
  docker-package:
    runs-on: ubuntu-latest 
    permissions: write-all
    if: ${{github.ref == 'refs/heads/main'}}
    steps:
    - uses: actions/checkout@v4
    - name: Login to Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker images
      run: |
        cp .env.juezvirtual .env
        cp .env.juezvirtual .env.production
        docker build . --build-arg --rm -t ghcr.io/onlinejudgebo/juezvirtualbo-admin-front:juezvirtual
    - name: Push Docker image to registry
      run: |
        docker push ghcr.io/onlinejudgebo/juezvirtualbo-admin-front:juezvirtual
